apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tilretteleggingsbehov-innsyn
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: { { image } }
  port: 3000
  ingresses:
    - https://www.nav.no/person/behov-for-tilrettelegging
  liveness:
    initialDelay: 5
    path: /person/behov-for-tilrettelegging/internal/isAlive
  readiness:
    initialDelay: 5
    path: /person/behov-for-tilrettelegging/internal/isReady
  accessPolicy:
    outbound:
      rules:
        - application: tilretteleggingsbehov-innsyn-redis
      external:
        - host: dekoratoren.nav.no
  envFrom:
    - secret: tilretteleggingsbehov-innsyn-redis-password
    - secret: tilretteleggingsbehov-innsyn-session-secret
