apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: tilretteleggingsbehov-innsyn
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{ image }}
    port: 3000
    ingresses:
        - https://tilretteleggingsbehov-innsyn.dev.nav.no/person/behov-for-tilrettelegging
    liveness:
        initialDelay: 5
        path: /person/behov-for-tilrettelegging/internal/isAlive
    readiness:
        initialDelay: 5
        path: /person/behov-for-tilrettelegging/internal/isReady
    vault:
        enabled: true
    env:
        - name: LOGIN_URL
          value: https://loginservice-q.nav.no/login?redirect=https://www-q0.nav.no/person/behov-for-tilrettelegging
        - name: APIGW_URL
          value: https://api-gw-q1.oera.no
