name: Bygg og deploy

on: [push]

env:
    IMAGE: ghcr.io/${{ github.repository }}/tilretteleggingsbehov-innsyn:${{ github.sha }}

jobs:
    bygg-og-push-docker-image:
        name: Bygg applikasjon
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: 'npm'
                  cache-dependency-path: |
                      package-lock.json
                      server/package-lock.json
            - name: Installer avhengigheter
              run: npm ci
            - name: Bygg applikasjon
              run: npm run build
            - name: Installer avhengigheter for server
              run: cd server && npm ci
            - name: Bygg server
              run: cd server && npm run build
            - name: Logg inn til Github
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Bygg og publiser Docker-image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ${{ env.IMAGE }}

    deploy-til-dev:
        name: Deploy til dev
        needs: bygg-og-push-docker-image
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/fjern-craco-og-less'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  RESOURCE: nais/nais-dev.yaml,nais/redis.yaml

    deploy-to-prod:
        name: Deploy til prod
        needs: deploy-til-dev
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: nais/nais-prod.yaml,nais/redis.yaml

    deploy-alerts:
        name: Deploy alerts to prod
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: nais/alerts.yaml

    snyk-monitor:
        name: Monitor dependencies with Snyk
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v1
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: 'npm'
            - name: Install Snyk CLI
              uses: snyk/actions/setup@master
            - name: Monitor dependencies in root with Snyk
              run: >
                  snyk monitor
                  --org=toi
                  --file=package.json
                  --project-name=${{ github.repository }}
                  --remote-repo-url=https://github.com/${{ github.repository }}.git
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Monitor dependencies in server with Snyk
              run: >
                  snyk monitor
                  --org=toi
                  --file=server/package.json
                  --project-name=${{ github.repository }}
                  --remote-repo-url=https://github.com/${{ github.repository }}.git
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
