name: Bygg og deploy

on: [push]

env:
    IMAGE: docker.pkg.github.com/${{ github.repository }}/tilretteleggingsbehov-innsyn:${{ github.sha }}

jobs:
    bygg-og-push-docker-image:
        name: Bygg applikasjon
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 10
            - uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Installer avhengigheter
              run: npm install
            - name: Bygg applikasjon
              run: |
                  export NODE_OPTIONS=--max-old-space-size=8192
                  npm run build
            - name: Installer avhengigheter for server
              run: npm run server:install
            - name: Bygg server
              run: npm run server:build
            - name: Bygg og publiser Docker-image
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  docker build --tag ${IMAGE} .
                  echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
                  docker push ${IMAGE}

    deploy-til-dev:
        name: Deploy til dev
        needs: bygg-og-push-docker-image
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/opprett-redis'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  RESOURCE: nais/nais-dev.yaml,nais/redis.yaml

    deploy-to-prod:
        name: Deploy til prod
        needs: deploy-til-dev
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: nais/nais-prod.yaml,nais/redis.yaml

    deploy-alerts:
        name: Deploy alerts to prod
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: nais/alerts.yaml
